# Generated by Django 4.0.6 on 2022-11-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_modelname_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='coupon_code',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
