# Generated by Django 4.0.6 on 2023-02-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_qr_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr',
            old_name='coupon_code',
            new_name='text',
        ),
    ]
